- 
  name: 'Install zabbix agent'
  hosts: all
  vars: 
        zabbix_server_ip: 113.196.57.243
        # zabbix_hostname = 
        
    
  tasks:
        - name: install zabbix_client
          shell: rpm -ivh http://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-agent-5.0.3-1.el7.x86_64.rpm 
        
        - name: Install zabbix agent
          shell: yum -y install zabbix-agent
        
        - name: modify zabbix server ip address
          shell: sed -i 's#Server=127.0.0.1#Server='{{zabbix_server_ip}}'#g' /etc/zabbix/zabbix_agentd.conf
          # lineinfile:

        - name: modify zabbix server active ip address
          shell: sed -i 's/ServerActive=127.0.0.1/ServerActive='{{zabbix_server_ip}}'/g' /etc/zabbix/zabbix_agentd.conf
        #  lineinfile:

        # - name: Enable remote command execution
        #  shell: sed -i 's/# EnableRemoteCommands=0/EnableRemoteCommands=1'/g /etc/zabbix/zabbix_agentd.conf
        # - name: Enable remote command logs
        #  shell: sed -i 's/# LogRemoteCommands=0/LogRemoteCommands=1'/g /etc/zabbix/zabbix_agentd.conf
        - name: modify zabbix agent hostname
          shell: sed -i 's/Hostname=Zabbix server/Hostname='{{zabbix_hostname}}'/g' /etc/zabbix/zabbix_agentd.conf
        
        - name: enable zabbix-agent
          shell: systemctl restart zabbix-agent ;systemctl enable zabbix-agent
        
